require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rails'
require 'capistrano/puma'
require 'capistrano/slackbot'
require 'capistrano/postgresql'
require 'whenever/capistrano'
